### ISSUE TITLE
halo wo kann ich hia piza besteln?

### ISSUE THREAD

**Issue by AlexSchmitz222** [eerieFoods/PizzaBrei#1]
heeloo, wo kan ich hia ein Piiza besteelln?
Das doch Pizaladn hia oda?

PS: Piza Salami bite als Schmuuutsii. dange

**Comment by AlexSchmitz222** [comment]
Heelloooo????

Wasn hia fürn schis sörfis?!

**Comment by Rexphel** [comment]
Bestellung aufgenommen. Pizza in Herstellung. Auslieferung bei bezahlung von 7000 BTC. Bei erhalt von 10000 BTC werden zwei pizzen geliefert.

**Comment by AlexSchmitz222** [comment]
Sheeeeeeesh. 
Das sind ja 20000WestBitcoin. 40000 OstBitcoin, 4000000 OstBitcoin auf dem Schwarzmarkt. Davon hätte man die DDR entschulden können

**Comment by Rexphel** [comment]
ich richte mich schlicht nach dem Marktpreis https://www.bankingclub.de/news/zeitreise/2010-zwei-pizzen-fuer-10-000-bitcoins-bitte/

**Comment by Rexphel** [comment]
Aufgrund dem Ausbleiben einer Zahlung bin ich gezwungen ihre Bestellung zu stonieren. Sry :(
